# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               Blog de Simon CHANU
tagline:             ''
description:         ''
url:                 http://blog.simon-chanu.eu
baseurl:             ''
gems:                [jekyll-paginate]
paginate:            5
paginate_path:       "page:num"

# About/contact
author:
  name:              Simon CHANU
  url:               simon.chanu@ensta-bretagne.fr

# Custom vars
version:             1.0.0
